// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"context"
	"ethfetcher/internal/ethereumfetcher/api"
	"ethfetcher/internal/ethereumfetcher/service"
	"sync"
)

type FakeEthereumClient struct {
	FetchTransactionByHashStub        func(context.Context, string) (api.Transaction, error)
	fetchTransactionByHashMutex       sync.RWMutex
	fetchTransactionByHashArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	fetchTransactionByHashReturns struct {
		result1 api.Transaction
		result2 error
	}
	fetchTransactionByHashReturnsOnCall map[int]struct {
		result1 api.Transaction
		result2 error
	}
	RlpHexToHashListStub        func(string) ([]string, error)
	rlpHexToHashListMutex       sync.RWMutex
	rlpHexToHashListArgsForCall []struct {
		arg1 string
	}
	rlpHexToHashListReturns struct {
		result1 []string
		result2 error
	}
	rlpHexToHashListReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEthereumClient) FetchTransactionByHash(arg1 context.Context, arg2 string) (api.Transaction, error) {
	fake.fetchTransactionByHashMutex.Lock()
	ret, specificReturn := fake.fetchTransactionByHashReturnsOnCall[len(fake.fetchTransactionByHashArgsForCall)]
	fake.fetchTransactionByHashArgsForCall = append(fake.fetchTransactionByHashArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FetchTransactionByHashStub
	fakeReturns := fake.fetchTransactionByHashReturns
	fake.recordInvocation("FetchTransactionByHash", []interface{}{arg1, arg2})
	fake.fetchTransactionByHashMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeEthereumClient) FetchTransactionByHashCallCount() int {
	fake.fetchTransactionByHashMutex.RLock()
	defer fake.fetchTransactionByHashMutex.RUnlock()
	return len(fake.fetchTransactionByHashArgsForCall)
}

func (fake *FakeEthereumClient) FetchTransactionByHashCalls(stub func(context.Context, string) (api.Transaction, error)) {
	fake.fetchTransactionByHashMutex.Lock()
	defer fake.fetchTransactionByHashMutex.Unlock()
	fake.FetchTransactionByHashStub = stub
}

func (fake *FakeEthereumClient) FetchTransactionByHashArgsForCall(i int) (context.Context, string) {
	fake.fetchTransactionByHashMutex.RLock()
	defer fake.fetchTransactionByHashMutex.RUnlock()
	argsForCall := fake.fetchTransactionByHashArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeEthereumClient) FetchTransactionByHashReturns(result1 api.Transaction, result2 error) {
	fake.fetchTransactionByHashMutex.Lock()
	defer fake.fetchTransactionByHashMutex.Unlock()
	fake.FetchTransactionByHashStub = nil
	fake.fetchTransactionByHashReturns = struct {
		result1 api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeEthereumClient) FetchTransactionByHashReturnsOnCall(i int, result1 api.Transaction, result2 error) {
	fake.fetchTransactionByHashMutex.Lock()
	defer fake.fetchTransactionByHashMutex.Unlock()
	fake.FetchTransactionByHashStub = nil
	if fake.fetchTransactionByHashReturnsOnCall == nil {
		fake.fetchTransactionByHashReturnsOnCall = make(map[int]struct {
			result1 api.Transaction
			result2 error
		})
	}
	fake.fetchTransactionByHashReturnsOnCall[i] = struct {
		result1 api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeEthereumClient) RlpHexToHashList(arg1 string) ([]string, error) {
	fake.rlpHexToHashListMutex.Lock()
	ret, specificReturn := fake.rlpHexToHashListReturnsOnCall[len(fake.rlpHexToHashListArgsForCall)]
	fake.rlpHexToHashListArgsForCall = append(fake.rlpHexToHashListArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.RlpHexToHashListStub
	fakeReturns := fake.rlpHexToHashListReturns
	fake.recordInvocation("RlpHexToHashList", []interface{}{arg1})
	fake.rlpHexToHashListMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeEthereumClient) RlpHexToHashListCallCount() int {
	fake.rlpHexToHashListMutex.RLock()
	defer fake.rlpHexToHashListMutex.RUnlock()
	return len(fake.rlpHexToHashListArgsForCall)
}

func (fake *FakeEthereumClient) RlpHexToHashListCalls(stub func(string) ([]string, error)) {
	fake.rlpHexToHashListMutex.Lock()
	defer fake.rlpHexToHashListMutex.Unlock()
	fake.RlpHexToHashListStub = stub
}

func (fake *FakeEthereumClient) RlpHexToHashListArgsForCall(i int) string {
	fake.rlpHexToHashListMutex.RLock()
	defer fake.rlpHexToHashListMutex.RUnlock()
	argsForCall := fake.rlpHexToHashListArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeEthereumClient) RlpHexToHashListReturns(result1 []string, result2 error) {
	fake.rlpHexToHashListMutex.Lock()
	defer fake.rlpHexToHashListMutex.Unlock()
	fake.RlpHexToHashListStub = nil
	fake.rlpHexToHashListReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeEthereumClient) RlpHexToHashListReturnsOnCall(i int, result1 []string, result2 error) {
	fake.rlpHexToHashListMutex.Lock()
	defer fake.rlpHexToHashListMutex.Unlock()
	fake.RlpHexToHashListStub = nil
	if fake.rlpHexToHashListReturnsOnCall == nil {
		fake.rlpHexToHashListReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.rlpHexToHashListReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeEthereumClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.fetchTransactionByHashMutex.RLock()
	defer fake.fetchTransactionByHashMutex.RUnlock()
	fake.rlpHexToHashListMutex.RLock()
	defer fake.rlpHexToHashListMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeEthereumClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.EthereumClient = new(FakeEthereumClient)
