// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"context"
	"ethfetcher/internal/ethereumfetcher/api"
	"ethfetcher/internal/ethereumfetcher/service"
	"sync"
)

type FakeStore struct {
	GetAllStub        func(context.Context) ([]api.Transaction, error)
	getAllMutex       sync.RWMutex
	getAllArgsForCall []struct {
		arg1 context.Context
	}
	getAllReturns struct {
		result1 []api.Transaction
		result2 error
	}
	getAllReturnsOnCall map[int]struct {
		result1 []api.Transaction
		result2 error
	}
	GetAllByUserStub        func(context.Context, string) ([]api.Transaction, error)
	getAllByUserMutex       sync.RWMutex
	getAllByUserArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getAllByUserReturns struct {
		result1 []api.Transaction
		result2 error
	}
	getAllByUserReturnsOnCall map[int]struct {
		result1 []api.Transaction
		result2 error
	}
	GetByHashStub        func(context.Context, string) (api.Transaction, error)
	getByHashMutex       sync.RWMutex
	getByHashArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getByHashReturns struct {
		result1 api.Transaction
		result2 error
	}
	getByHashReturnsOnCall map[int]struct {
		result1 api.Transaction
		result2 error
	}
	InsertStub        func(context.Context, api.Transaction) error
	insertMutex       sync.RWMutex
	insertArgsForCall []struct {
		arg1 context.Context
		arg2 api.Transaction
	}
	insertReturns struct {
		result1 error
	}
	insertReturnsOnCall map[int]struct {
		result1 error
	}
	InsertUserTransactionsStub        func(context.Context, string, []api.Transaction) error
	insertUserTransactionsMutex       sync.RWMutex
	insertUserTransactionsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []api.Transaction
	}
	insertUserTransactionsReturns struct {
		result1 error
	}
	insertUserTransactionsReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStore) GetAll(arg1 context.Context) ([]api.Transaction, error) {
	fake.getAllMutex.Lock()
	ret, specificReturn := fake.getAllReturnsOnCall[len(fake.getAllArgsForCall)]
	fake.getAllArgsForCall = append(fake.getAllArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetAllStub
	fakeReturns := fake.getAllReturns
	fake.recordInvocation("GetAll", []interface{}{arg1})
	fake.getAllMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) GetAllCallCount() int {
	fake.getAllMutex.RLock()
	defer fake.getAllMutex.RUnlock()
	return len(fake.getAllArgsForCall)
}

func (fake *FakeStore) GetAllCalls(stub func(context.Context) ([]api.Transaction, error)) {
	fake.getAllMutex.Lock()
	defer fake.getAllMutex.Unlock()
	fake.GetAllStub = stub
}

func (fake *FakeStore) GetAllArgsForCall(i int) context.Context {
	fake.getAllMutex.RLock()
	defer fake.getAllMutex.RUnlock()
	argsForCall := fake.getAllArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStore) GetAllReturns(result1 []api.Transaction, result2 error) {
	fake.getAllMutex.Lock()
	defer fake.getAllMutex.Unlock()
	fake.GetAllStub = nil
	fake.getAllReturns = struct {
		result1 []api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) GetAllReturnsOnCall(i int, result1 []api.Transaction, result2 error) {
	fake.getAllMutex.Lock()
	defer fake.getAllMutex.Unlock()
	fake.GetAllStub = nil
	if fake.getAllReturnsOnCall == nil {
		fake.getAllReturnsOnCall = make(map[int]struct {
			result1 []api.Transaction
			result2 error
		})
	}
	fake.getAllReturnsOnCall[i] = struct {
		result1 []api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) GetAllByUser(arg1 context.Context, arg2 string) ([]api.Transaction, error) {
	fake.getAllByUserMutex.Lock()
	ret, specificReturn := fake.getAllByUserReturnsOnCall[len(fake.getAllByUserArgsForCall)]
	fake.getAllByUserArgsForCall = append(fake.getAllByUserArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetAllByUserStub
	fakeReturns := fake.getAllByUserReturns
	fake.recordInvocation("GetAllByUser", []interface{}{arg1, arg2})
	fake.getAllByUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) GetAllByUserCallCount() int {
	fake.getAllByUserMutex.RLock()
	defer fake.getAllByUserMutex.RUnlock()
	return len(fake.getAllByUserArgsForCall)
}

func (fake *FakeStore) GetAllByUserCalls(stub func(context.Context, string) ([]api.Transaction, error)) {
	fake.getAllByUserMutex.Lock()
	defer fake.getAllByUserMutex.Unlock()
	fake.GetAllByUserStub = stub
}

func (fake *FakeStore) GetAllByUserArgsForCall(i int) (context.Context, string) {
	fake.getAllByUserMutex.RLock()
	defer fake.getAllByUserMutex.RUnlock()
	argsForCall := fake.getAllByUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) GetAllByUserReturns(result1 []api.Transaction, result2 error) {
	fake.getAllByUserMutex.Lock()
	defer fake.getAllByUserMutex.Unlock()
	fake.GetAllByUserStub = nil
	fake.getAllByUserReturns = struct {
		result1 []api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) GetAllByUserReturnsOnCall(i int, result1 []api.Transaction, result2 error) {
	fake.getAllByUserMutex.Lock()
	defer fake.getAllByUserMutex.Unlock()
	fake.GetAllByUserStub = nil
	if fake.getAllByUserReturnsOnCall == nil {
		fake.getAllByUserReturnsOnCall = make(map[int]struct {
			result1 []api.Transaction
			result2 error
		})
	}
	fake.getAllByUserReturnsOnCall[i] = struct {
		result1 []api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) GetByHash(arg1 context.Context, arg2 string) (api.Transaction, error) {
	fake.getByHashMutex.Lock()
	ret, specificReturn := fake.getByHashReturnsOnCall[len(fake.getByHashArgsForCall)]
	fake.getByHashArgsForCall = append(fake.getByHashArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetByHashStub
	fakeReturns := fake.getByHashReturns
	fake.recordInvocation("GetByHash", []interface{}{arg1, arg2})
	fake.getByHashMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) GetByHashCallCount() int {
	fake.getByHashMutex.RLock()
	defer fake.getByHashMutex.RUnlock()
	return len(fake.getByHashArgsForCall)
}

func (fake *FakeStore) GetByHashCalls(stub func(context.Context, string) (api.Transaction, error)) {
	fake.getByHashMutex.Lock()
	defer fake.getByHashMutex.Unlock()
	fake.GetByHashStub = stub
}

func (fake *FakeStore) GetByHashArgsForCall(i int) (context.Context, string) {
	fake.getByHashMutex.RLock()
	defer fake.getByHashMutex.RUnlock()
	argsForCall := fake.getByHashArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) GetByHashReturns(result1 api.Transaction, result2 error) {
	fake.getByHashMutex.Lock()
	defer fake.getByHashMutex.Unlock()
	fake.GetByHashStub = nil
	fake.getByHashReturns = struct {
		result1 api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) GetByHashReturnsOnCall(i int, result1 api.Transaction, result2 error) {
	fake.getByHashMutex.Lock()
	defer fake.getByHashMutex.Unlock()
	fake.GetByHashStub = nil
	if fake.getByHashReturnsOnCall == nil {
		fake.getByHashReturnsOnCall = make(map[int]struct {
			result1 api.Transaction
			result2 error
		})
	}
	fake.getByHashReturnsOnCall[i] = struct {
		result1 api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Insert(arg1 context.Context, arg2 api.Transaction) error {
	fake.insertMutex.Lock()
	ret, specificReturn := fake.insertReturnsOnCall[len(fake.insertArgsForCall)]
	fake.insertArgsForCall = append(fake.insertArgsForCall, struct {
		arg1 context.Context
		arg2 api.Transaction
	}{arg1, arg2})
	stub := fake.InsertStub
	fakeReturns := fake.insertReturns
	fake.recordInvocation("Insert", []interface{}{arg1, arg2})
	fake.insertMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) InsertCallCount() int {
	fake.insertMutex.RLock()
	defer fake.insertMutex.RUnlock()
	return len(fake.insertArgsForCall)
}

func (fake *FakeStore) InsertCalls(stub func(context.Context, api.Transaction) error) {
	fake.insertMutex.Lock()
	defer fake.insertMutex.Unlock()
	fake.InsertStub = stub
}

func (fake *FakeStore) InsertArgsForCall(i int) (context.Context, api.Transaction) {
	fake.insertMutex.RLock()
	defer fake.insertMutex.RUnlock()
	argsForCall := fake.insertArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) InsertReturns(result1 error) {
	fake.insertMutex.Lock()
	defer fake.insertMutex.Unlock()
	fake.InsertStub = nil
	fake.insertReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) InsertReturnsOnCall(i int, result1 error) {
	fake.insertMutex.Lock()
	defer fake.insertMutex.Unlock()
	fake.InsertStub = nil
	if fake.insertReturnsOnCall == nil {
		fake.insertReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.insertReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) InsertUserTransactions(arg1 context.Context, arg2 string, arg3 []api.Transaction) error {
	var arg3Copy []api.Transaction
	if arg3 != nil {
		arg3Copy = make([]api.Transaction, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.insertUserTransactionsMutex.Lock()
	ret, specificReturn := fake.insertUserTransactionsReturnsOnCall[len(fake.insertUserTransactionsArgsForCall)]
	fake.insertUserTransactionsArgsForCall = append(fake.insertUserTransactionsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []api.Transaction
	}{arg1, arg2, arg3Copy})
	stub := fake.InsertUserTransactionsStub
	fakeReturns := fake.insertUserTransactionsReturns
	fake.recordInvocation("InsertUserTransactions", []interface{}{arg1, arg2, arg3Copy})
	fake.insertUserTransactionsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) InsertUserTransactionsCallCount() int {
	fake.insertUserTransactionsMutex.RLock()
	defer fake.insertUserTransactionsMutex.RUnlock()
	return len(fake.insertUserTransactionsArgsForCall)
}

func (fake *FakeStore) InsertUserTransactionsCalls(stub func(context.Context, string, []api.Transaction) error) {
	fake.insertUserTransactionsMutex.Lock()
	defer fake.insertUserTransactionsMutex.Unlock()
	fake.InsertUserTransactionsStub = stub
}

func (fake *FakeStore) InsertUserTransactionsArgsForCall(i int) (context.Context, string, []api.Transaction) {
	fake.insertUserTransactionsMutex.RLock()
	defer fake.insertUserTransactionsMutex.RUnlock()
	argsForCall := fake.insertUserTransactionsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStore) InsertUserTransactionsReturns(result1 error) {
	fake.insertUserTransactionsMutex.Lock()
	defer fake.insertUserTransactionsMutex.Unlock()
	fake.InsertUserTransactionsStub = nil
	fake.insertUserTransactionsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) InsertUserTransactionsReturnsOnCall(i int, result1 error) {
	fake.insertUserTransactionsMutex.Lock()
	defer fake.insertUserTransactionsMutex.Unlock()
	fake.InsertUserTransactionsStub = nil
	if fake.insertUserTransactionsReturnsOnCall == nil {
		fake.insertUserTransactionsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.insertUserTransactionsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAllMutex.RLock()
	defer fake.getAllMutex.RUnlock()
	fake.getAllByUserMutex.RLock()
	defer fake.getAllByUserMutex.RUnlock()
	fake.getByHashMutex.RLock()
	defer fake.getByHashMutex.RUnlock()
	fake.insertMutex.RLock()
	defer fake.insertMutex.RUnlock()
	fake.insertUserTransactionsMutex.RLock()
	defer fake.insertUserTransactionsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.Store = new(FakeStore)
