// Code generated by counterfeiter. DO NOT EDIT.
package processfakes

import (
	"context"
	"ethfetcher/internal/auth/process"
	"sync"
)

type FakeService struct {
	AuthenticateStub        func(context.Context, string, string) (string, error)
	authenticateMutex       sync.RWMutex
	authenticateArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	authenticateReturns struct {
		result1 string
		result2 error
	}
	authenticateReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	DeleteExpiredTokensStub        func(context.Context) error
	deleteExpiredTokensMutex       sync.RWMutex
	deleteExpiredTokensArgsForCall []struct {
		arg1 context.Context
	}
	deleteExpiredTokensReturns struct {
		result1 error
	}
	deleteExpiredTokensReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) Authenticate(arg1 context.Context, arg2 string, arg3 string) (string, error) {
	fake.authenticateMutex.Lock()
	ret, specificReturn := fake.authenticateReturnsOnCall[len(fake.authenticateArgsForCall)]
	fake.authenticateArgsForCall = append(fake.authenticateArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.AuthenticateStub
	fakeReturns := fake.authenticateReturns
	fake.recordInvocation("Authenticate", []interface{}{arg1, arg2, arg3})
	fake.authenticateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) AuthenticateCallCount() int {
	fake.authenticateMutex.RLock()
	defer fake.authenticateMutex.RUnlock()
	return len(fake.authenticateArgsForCall)
}

func (fake *FakeService) AuthenticateCalls(stub func(context.Context, string, string) (string, error)) {
	fake.authenticateMutex.Lock()
	defer fake.authenticateMutex.Unlock()
	fake.AuthenticateStub = stub
}

func (fake *FakeService) AuthenticateArgsForCall(i int) (context.Context, string, string) {
	fake.authenticateMutex.RLock()
	defer fake.authenticateMutex.RUnlock()
	argsForCall := fake.authenticateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) AuthenticateReturns(result1 string, result2 error) {
	fake.authenticateMutex.Lock()
	defer fake.authenticateMutex.Unlock()
	fake.AuthenticateStub = nil
	fake.authenticateReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeService) AuthenticateReturnsOnCall(i int, result1 string, result2 error) {
	fake.authenticateMutex.Lock()
	defer fake.authenticateMutex.Unlock()
	fake.AuthenticateStub = nil
	if fake.authenticateReturnsOnCall == nil {
		fake.authenticateReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.authenticateReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeService) DeleteExpiredTokens(arg1 context.Context) error {
	fake.deleteExpiredTokensMutex.Lock()
	ret, specificReturn := fake.deleteExpiredTokensReturnsOnCall[len(fake.deleteExpiredTokensArgsForCall)]
	fake.deleteExpiredTokensArgsForCall = append(fake.deleteExpiredTokensArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.DeleteExpiredTokensStub
	fakeReturns := fake.deleteExpiredTokensReturns
	fake.recordInvocation("DeleteExpiredTokens", []interface{}{arg1})
	fake.deleteExpiredTokensMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) DeleteExpiredTokensCallCount() int {
	fake.deleteExpiredTokensMutex.RLock()
	defer fake.deleteExpiredTokensMutex.RUnlock()
	return len(fake.deleteExpiredTokensArgsForCall)
}

func (fake *FakeService) DeleteExpiredTokensCalls(stub func(context.Context) error) {
	fake.deleteExpiredTokensMutex.Lock()
	defer fake.deleteExpiredTokensMutex.Unlock()
	fake.DeleteExpiredTokensStub = stub
}

func (fake *FakeService) DeleteExpiredTokensArgsForCall(i int) context.Context {
	fake.deleteExpiredTokensMutex.RLock()
	defer fake.deleteExpiredTokensMutex.RUnlock()
	argsForCall := fake.deleteExpiredTokensArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) DeleteExpiredTokensReturns(result1 error) {
	fake.deleteExpiredTokensMutex.Lock()
	defer fake.deleteExpiredTokensMutex.Unlock()
	fake.DeleteExpiredTokensStub = nil
	fake.deleteExpiredTokensReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) DeleteExpiredTokensReturnsOnCall(i int, result1 error) {
	fake.deleteExpiredTokensMutex.Lock()
	defer fake.deleteExpiredTokensMutex.Unlock()
	fake.DeleteExpiredTokensStub = nil
	if fake.deleteExpiredTokensReturnsOnCall == nil {
		fake.deleteExpiredTokensReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteExpiredTokensReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.authenticateMutex.RLock()
	defer fake.authenticateMutex.RUnlock()
	fake.deleteExpiredTokensMutex.RLock()
	defer fake.deleteExpiredTokensMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ process.Service = new(FakeService)
