// Code generated by counterfeiter. DO NOT EDIT.
package processfakes

import (
	"context"
	"ethfetcher/internal/ethereumfetcher/api"
	"ethfetcher/internal/ethereumfetcher/process"
	"sync"
)

type FakeService struct {
	GetAllEthTransactionsStub        func(context.Context) ([]api.Transaction, error)
	getAllEthTransactionsMutex       sync.RWMutex
	getAllEthTransactionsArgsForCall []struct {
		arg1 context.Context
	}
	getAllEthTransactionsReturns struct {
		result1 []api.Transaction
		result2 error
	}
	getAllEthTransactionsReturnsOnCall map[int]struct {
		result1 []api.Transaction
		result2 error
	}
	GetEthTransactionsStub        func(context.Context, []string) ([]api.Transaction, error)
	getEthTransactionsMutex       sync.RWMutex
	getEthTransactionsArgsForCall []struct {
		arg1 context.Context
		arg2 []string
	}
	getEthTransactionsReturns struct {
		result1 []api.Transaction
		result2 error
	}
	getEthTransactionsReturnsOnCall map[int]struct {
		result1 []api.Transaction
		result2 error
	}
	GetEthTransactionsByRLPStub        func(context.Context, string) ([]api.Transaction, error)
	getEthTransactionsByRLPMutex       sync.RWMutex
	getEthTransactionsByRLPArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getEthTransactionsByRLPReturns struct {
		result1 []api.Transaction
		result2 error
	}
	getEthTransactionsByRLPReturnsOnCall map[int]struct {
		result1 []api.Transaction
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) GetAllEthTransactions(arg1 context.Context) ([]api.Transaction, error) {
	fake.getAllEthTransactionsMutex.Lock()
	ret, specificReturn := fake.getAllEthTransactionsReturnsOnCall[len(fake.getAllEthTransactionsArgsForCall)]
	fake.getAllEthTransactionsArgsForCall = append(fake.getAllEthTransactionsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetAllEthTransactionsStub
	fakeReturns := fake.getAllEthTransactionsReturns
	fake.recordInvocation("GetAllEthTransactions", []interface{}{arg1})
	fake.getAllEthTransactionsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) GetAllEthTransactionsCallCount() int {
	fake.getAllEthTransactionsMutex.RLock()
	defer fake.getAllEthTransactionsMutex.RUnlock()
	return len(fake.getAllEthTransactionsArgsForCall)
}

func (fake *FakeService) GetAllEthTransactionsCalls(stub func(context.Context) ([]api.Transaction, error)) {
	fake.getAllEthTransactionsMutex.Lock()
	defer fake.getAllEthTransactionsMutex.Unlock()
	fake.GetAllEthTransactionsStub = stub
}

func (fake *FakeService) GetAllEthTransactionsArgsForCall(i int) context.Context {
	fake.getAllEthTransactionsMutex.RLock()
	defer fake.getAllEthTransactionsMutex.RUnlock()
	argsForCall := fake.getAllEthTransactionsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) GetAllEthTransactionsReturns(result1 []api.Transaction, result2 error) {
	fake.getAllEthTransactionsMutex.Lock()
	defer fake.getAllEthTransactionsMutex.Unlock()
	fake.GetAllEthTransactionsStub = nil
	fake.getAllEthTransactionsReturns = struct {
		result1 []api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetAllEthTransactionsReturnsOnCall(i int, result1 []api.Transaction, result2 error) {
	fake.getAllEthTransactionsMutex.Lock()
	defer fake.getAllEthTransactionsMutex.Unlock()
	fake.GetAllEthTransactionsStub = nil
	if fake.getAllEthTransactionsReturnsOnCall == nil {
		fake.getAllEthTransactionsReturnsOnCall = make(map[int]struct {
			result1 []api.Transaction
			result2 error
		})
	}
	fake.getAllEthTransactionsReturnsOnCall[i] = struct {
		result1 []api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetEthTransactions(arg1 context.Context, arg2 []string) ([]api.Transaction, error) {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.getEthTransactionsMutex.Lock()
	ret, specificReturn := fake.getEthTransactionsReturnsOnCall[len(fake.getEthTransactionsArgsForCall)]
	fake.getEthTransactionsArgsForCall = append(fake.getEthTransactionsArgsForCall, struct {
		arg1 context.Context
		arg2 []string
	}{arg1, arg2Copy})
	stub := fake.GetEthTransactionsStub
	fakeReturns := fake.getEthTransactionsReturns
	fake.recordInvocation("GetEthTransactions", []interface{}{arg1, arg2Copy})
	fake.getEthTransactionsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) GetEthTransactionsCallCount() int {
	fake.getEthTransactionsMutex.RLock()
	defer fake.getEthTransactionsMutex.RUnlock()
	return len(fake.getEthTransactionsArgsForCall)
}

func (fake *FakeService) GetEthTransactionsCalls(stub func(context.Context, []string) ([]api.Transaction, error)) {
	fake.getEthTransactionsMutex.Lock()
	defer fake.getEthTransactionsMutex.Unlock()
	fake.GetEthTransactionsStub = stub
}

func (fake *FakeService) GetEthTransactionsArgsForCall(i int) (context.Context, []string) {
	fake.getEthTransactionsMutex.RLock()
	defer fake.getEthTransactionsMutex.RUnlock()
	argsForCall := fake.getEthTransactionsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) GetEthTransactionsReturns(result1 []api.Transaction, result2 error) {
	fake.getEthTransactionsMutex.Lock()
	defer fake.getEthTransactionsMutex.Unlock()
	fake.GetEthTransactionsStub = nil
	fake.getEthTransactionsReturns = struct {
		result1 []api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetEthTransactionsReturnsOnCall(i int, result1 []api.Transaction, result2 error) {
	fake.getEthTransactionsMutex.Lock()
	defer fake.getEthTransactionsMutex.Unlock()
	fake.GetEthTransactionsStub = nil
	if fake.getEthTransactionsReturnsOnCall == nil {
		fake.getEthTransactionsReturnsOnCall = make(map[int]struct {
			result1 []api.Transaction
			result2 error
		})
	}
	fake.getEthTransactionsReturnsOnCall[i] = struct {
		result1 []api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetEthTransactionsByRLP(arg1 context.Context, arg2 string) ([]api.Transaction, error) {
	fake.getEthTransactionsByRLPMutex.Lock()
	ret, specificReturn := fake.getEthTransactionsByRLPReturnsOnCall[len(fake.getEthTransactionsByRLPArgsForCall)]
	fake.getEthTransactionsByRLPArgsForCall = append(fake.getEthTransactionsByRLPArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetEthTransactionsByRLPStub
	fakeReturns := fake.getEthTransactionsByRLPReturns
	fake.recordInvocation("GetEthTransactionsByRLP", []interface{}{arg1, arg2})
	fake.getEthTransactionsByRLPMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) GetEthTransactionsByRLPCallCount() int {
	fake.getEthTransactionsByRLPMutex.RLock()
	defer fake.getEthTransactionsByRLPMutex.RUnlock()
	return len(fake.getEthTransactionsByRLPArgsForCall)
}

func (fake *FakeService) GetEthTransactionsByRLPCalls(stub func(context.Context, string) ([]api.Transaction, error)) {
	fake.getEthTransactionsByRLPMutex.Lock()
	defer fake.getEthTransactionsByRLPMutex.Unlock()
	fake.GetEthTransactionsByRLPStub = stub
}

func (fake *FakeService) GetEthTransactionsByRLPArgsForCall(i int) (context.Context, string) {
	fake.getEthTransactionsByRLPMutex.RLock()
	defer fake.getEthTransactionsByRLPMutex.RUnlock()
	argsForCall := fake.getEthTransactionsByRLPArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) GetEthTransactionsByRLPReturns(result1 []api.Transaction, result2 error) {
	fake.getEthTransactionsByRLPMutex.Lock()
	defer fake.getEthTransactionsByRLPMutex.Unlock()
	fake.GetEthTransactionsByRLPStub = nil
	fake.getEthTransactionsByRLPReturns = struct {
		result1 []api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetEthTransactionsByRLPReturnsOnCall(i int, result1 []api.Transaction, result2 error) {
	fake.getEthTransactionsByRLPMutex.Lock()
	defer fake.getEthTransactionsByRLPMutex.Unlock()
	fake.GetEthTransactionsByRLPStub = nil
	if fake.getEthTransactionsByRLPReturnsOnCall == nil {
		fake.getEthTransactionsByRLPReturnsOnCall = make(map[int]struct {
			result1 []api.Transaction
			result2 error
		})
	}
	fake.getEthTransactionsByRLPReturnsOnCall[i] = struct {
		result1 []api.Transaction
		result2 error
	}{result1, result2}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAllEthTransactionsMutex.RLock()
	defer fake.getAllEthTransactionsMutex.RUnlock()
	fake.getEthTransactionsMutex.RLock()
	defer fake.getEthTransactionsMutex.RUnlock()
	fake.getEthTransactionsByRLPMutex.RLock()
	defer fake.getEthTransactionsByRLPMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ process.Service = new(FakeService)
