// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"context"
	"ethfetcher/internal/auth/model"
	"ethfetcher/internal/auth/service"
	"sync"
)

type FakeStore struct {
	DeleteExpiredTokensStub        func(context.Context) error
	deleteExpiredTokensMutex       sync.RWMutex
	deleteExpiredTokensArgsForCall []struct {
		arg1 context.Context
	}
	deleteExpiredTokensReturns struct {
		result1 error
	}
	deleteExpiredTokensReturnsOnCall map[int]struct {
		result1 error
	}
	IsTokenValidStub        func(context.Context, string) (bool, string, error)
	isTokenValidMutex       sync.RWMutex
	isTokenValidArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	isTokenValidReturns struct {
		result1 bool
		result2 string
		result3 error
	}
	isTokenValidReturnsOnCall map[int]struct {
		result1 bool
		result2 string
		result3 error
	}
	StoreTokenStub        func(context.Context, model.Token) error
	storeTokenMutex       sync.RWMutex
	storeTokenArgsForCall []struct {
		arg1 context.Context
		arg2 model.Token
	}
	storeTokenReturns struct {
		result1 error
	}
	storeTokenReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateUserStub        func(context.Context, string, string) (bool, error)
	validateUserMutex       sync.RWMutex
	validateUserArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	validateUserReturns struct {
		result1 bool
		result2 error
	}
	validateUserReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStore) DeleteExpiredTokens(arg1 context.Context) error {
	fake.deleteExpiredTokensMutex.Lock()
	ret, specificReturn := fake.deleteExpiredTokensReturnsOnCall[len(fake.deleteExpiredTokensArgsForCall)]
	fake.deleteExpiredTokensArgsForCall = append(fake.deleteExpiredTokensArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.DeleteExpiredTokensStub
	fakeReturns := fake.deleteExpiredTokensReturns
	fake.recordInvocation("DeleteExpiredTokens", []interface{}{arg1})
	fake.deleteExpiredTokensMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) DeleteExpiredTokensCallCount() int {
	fake.deleteExpiredTokensMutex.RLock()
	defer fake.deleteExpiredTokensMutex.RUnlock()
	return len(fake.deleteExpiredTokensArgsForCall)
}

func (fake *FakeStore) DeleteExpiredTokensCalls(stub func(context.Context) error) {
	fake.deleteExpiredTokensMutex.Lock()
	defer fake.deleteExpiredTokensMutex.Unlock()
	fake.DeleteExpiredTokensStub = stub
}

func (fake *FakeStore) DeleteExpiredTokensArgsForCall(i int) context.Context {
	fake.deleteExpiredTokensMutex.RLock()
	defer fake.deleteExpiredTokensMutex.RUnlock()
	argsForCall := fake.deleteExpiredTokensArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStore) DeleteExpiredTokensReturns(result1 error) {
	fake.deleteExpiredTokensMutex.Lock()
	defer fake.deleteExpiredTokensMutex.Unlock()
	fake.DeleteExpiredTokensStub = nil
	fake.deleteExpiredTokensReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) DeleteExpiredTokensReturnsOnCall(i int, result1 error) {
	fake.deleteExpiredTokensMutex.Lock()
	defer fake.deleteExpiredTokensMutex.Unlock()
	fake.DeleteExpiredTokensStub = nil
	if fake.deleteExpiredTokensReturnsOnCall == nil {
		fake.deleteExpiredTokensReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteExpiredTokensReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) IsTokenValid(arg1 context.Context, arg2 string) (bool, string, error) {
	fake.isTokenValidMutex.Lock()
	ret, specificReturn := fake.isTokenValidReturnsOnCall[len(fake.isTokenValidArgsForCall)]
	fake.isTokenValidArgsForCall = append(fake.isTokenValidArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.IsTokenValidStub
	fakeReturns := fake.isTokenValidReturns
	fake.recordInvocation("IsTokenValid", []interface{}{arg1, arg2})
	fake.isTokenValidMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeStore) IsTokenValidCallCount() int {
	fake.isTokenValidMutex.RLock()
	defer fake.isTokenValidMutex.RUnlock()
	return len(fake.isTokenValidArgsForCall)
}

func (fake *FakeStore) IsTokenValidCalls(stub func(context.Context, string) (bool, string, error)) {
	fake.isTokenValidMutex.Lock()
	defer fake.isTokenValidMutex.Unlock()
	fake.IsTokenValidStub = stub
}

func (fake *FakeStore) IsTokenValidArgsForCall(i int) (context.Context, string) {
	fake.isTokenValidMutex.RLock()
	defer fake.isTokenValidMutex.RUnlock()
	argsForCall := fake.isTokenValidArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) IsTokenValidReturns(result1 bool, result2 string, result3 error) {
	fake.isTokenValidMutex.Lock()
	defer fake.isTokenValidMutex.Unlock()
	fake.IsTokenValidStub = nil
	fake.isTokenValidReturns = struct {
		result1 bool
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeStore) IsTokenValidReturnsOnCall(i int, result1 bool, result2 string, result3 error) {
	fake.isTokenValidMutex.Lock()
	defer fake.isTokenValidMutex.Unlock()
	fake.IsTokenValidStub = nil
	if fake.isTokenValidReturnsOnCall == nil {
		fake.isTokenValidReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 string
			result3 error
		})
	}
	fake.isTokenValidReturnsOnCall[i] = struct {
		result1 bool
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeStore) StoreToken(arg1 context.Context, arg2 model.Token) error {
	fake.storeTokenMutex.Lock()
	ret, specificReturn := fake.storeTokenReturnsOnCall[len(fake.storeTokenArgsForCall)]
	fake.storeTokenArgsForCall = append(fake.storeTokenArgsForCall, struct {
		arg1 context.Context
		arg2 model.Token
	}{arg1, arg2})
	stub := fake.StoreTokenStub
	fakeReturns := fake.storeTokenReturns
	fake.recordInvocation("StoreToken", []interface{}{arg1, arg2})
	fake.storeTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) StoreTokenCallCount() int {
	fake.storeTokenMutex.RLock()
	defer fake.storeTokenMutex.RUnlock()
	return len(fake.storeTokenArgsForCall)
}

func (fake *FakeStore) StoreTokenCalls(stub func(context.Context, model.Token) error) {
	fake.storeTokenMutex.Lock()
	defer fake.storeTokenMutex.Unlock()
	fake.StoreTokenStub = stub
}

func (fake *FakeStore) StoreTokenArgsForCall(i int) (context.Context, model.Token) {
	fake.storeTokenMutex.RLock()
	defer fake.storeTokenMutex.RUnlock()
	argsForCall := fake.storeTokenArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) StoreTokenReturns(result1 error) {
	fake.storeTokenMutex.Lock()
	defer fake.storeTokenMutex.Unlock()
	fake.StoreTokenStub = nil
	fake.storeTokenReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) StoreTokenReturnsOnCall(i int, result1 error) {
	fake.storeTokenMutex.Lock()
	defer fake.storeTokenMutex.Unlock()
	fake.StoreTokenStub = nil
	if fake.storeTokenReturnsOnCall == nil {
		fake.storeTokenReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.storeTokenReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) ValidateUser(arg1 context.Context, arg2 string, arg3 string) (bool, error) {
	fake.validateUserMutex.Lock()
	ret, specificReturn := fake.validateUserReturnsOnCall[len(fake.validateUserArgsForCall)]
	fake.validateUserArgsForCall = append(fake.validateUserArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ValidateUserStub
	fakeReturns := fake.validateUserReturns
	fake.recordInvocation("ValidateUser", []interface{}{arg1, arg2, arg3})
	fake.validateUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) ValidateUserCallCount() int {
	fake.validateUserMutex.RLock()
	defer fake.validateUserMutex.RUnlock()
	return len(fake.validateUserArgsForCall)
}

func (fake *FakeStore) ValidateUserCalls(stub func(context.Context, string, string) (bool, error)) {
	fake.validateUserMutex.Lock()
	defer fake.validateUserMutex.Unlock()
	fake.ValidateUserStub = stub
}

func (fake *FakeStore) ValidateUserArgsForCall(i int) (context.Context, string, string) {
	fake.validateUserMutex.RLock()
	defer fake.validateUserMutex.RUnlock()
	argsForCall := fake.validateUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStore) ValidateUserReturns(result1 bool, result2 error) {
	fake.validateUserMutex.Lock()
	defer fake.validateUserMutex.Unlock()
	fake.ValidateUserStub = nil
	fake.validateUserReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) ValidateUserReturnsOnCall(i int, result1 bool, result2 error) {
	fake.validateUserMutex.Lock()
	defer fake.validateUserMutex.Unlock()
	fake.ValidateUserStub = nil
	if fake.validateUserReturnsOnCall == nil {
		fake.validateUserReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.validateUserReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteExpiredTokensMutex.RLock()
	defer fake.deleteExpiredTokensMutex.RUnlock()
	fake.isTokenValidMutex.RLock()
	defer fake.isTokenValidMutex.RUnlock()
	fake.storeTokenMutex.RLock()
	defer fake.storeTokenMutex.RUnlock()
	fake.validateUserMutex.RLock()
	defer fake.validateUserMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.Store = new(FakeStore)
